# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4eca1ba6fa15b0bfbdac7a8871f8cbc1c2c06b71ec1b45d3795dea1912bbfc23132fb29987087c864e8af5c32ca71c17e507dd53970741024ec9980f12789c44

test:
  secret_key_base: 48f642cf5b2589a553a7e73cdec239478c628b23fdb2d182cd105d27cf7b764fb1afd4c0131b3a784b45255e0272627f8c81b6775f98bad2a66d3662d5393b83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
